[package]
name = "tipfinity"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "3.0.7"
solana-sdk = "3.0.0"
solana-transaction-status = "3.0.7"
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
axum = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "macros", "chrono", "bigdecimal"] }
dotenv = "0.15"
hyper = "1.7.0"
tower-http = { version = "0.6.4", features = ["cors"] }
chrono = { version = "0.4", features = ["serde", "clock"] }
tracing = "0.1"
tracing-subscriber = "0.3"
bs58 = "0.5.1"
bigdecimal = "0.4.9"
resend-rs = "0.18.0"
